name: Deploy Staging

on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to staging EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.STAGING }}
          script: |

            cd /var/www/myapp/laravel-backend

            echo "Logging into GHCR..."

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
              -u ${{ github.repository_owner }} \
              --password-stdin


            echo "Pulling latest staging image..."

            docker pull ghcr.io/bilalfuldacs/laravel-backend:staging


            echo "Restarting containers..."

            docker compose -f docker-compose.prod.yml down

            docker compose -f docker-compose.prod.yml up -d


            sleep 20


            echo "Running Laravel migrations..."

            docker compose exec -T app php artisan migrate --force

            docker compose exec -T app php artisan config:clear

            docker compose exec -T app php artisan cache:clear